CONTROL_CODE_PREFIX='\033['
CONTROL_CODE_SPERATOR=';'
CONTROL_CODE_SUFFIX='m'

CONTROL_CODE_CLOSE='0'
CONTROL_CODE_HIGHLIGHT='1'
CONTROL_CODE_UNDERLINE='4'
CONTROL_CODE_FLASHING='5'
CONTROL_CODE_REVERSE_DISPLAY='7'
CONTROL_CODE_HIDE='8'

TEXT_COLOR_BLACK='30'
TEXT_COLOR_RED='31'
TEXT_COLOR_GREEN='32'
TEXT_COLOR_YELLOW='33'
TEXT_COLOR_BLUE='34'
TEXT_COLOR_PINK='35'
TEXT_COLOR_DEEP_BLUE='36'
TEXT_COLOR_WHITE='37'

BACKGROUND_COLOR_BLACK='40'
BACKGROUND_COLOR_RED='41'
BACKGROUND_COLOR_GREEN='42'
BACKGROUND_COLOR_YELLOW='43'
BACKGROUND_COLOR_BLUE='44'
BACKGROUND_COLOR_PINK='45'
BACKGROUND_COLOR_DEEP_BLUE='46'
BACKGROUND_COLOR_WHITE='47'

GOPATH=${HOME}/code
CLONE_PATH=/usr/local/src
APP_PATH=/usr/local/app
BIN_PATH=/usr/local/bin
