set -uo pipefail

source $(dirname ${BASH_SOURCE[0]})/constant.sh

export GOPATH=${CODE_PATH}
export GOROOT=${APP_PATH}/go
export GOBIN=$BIN_PATH
#export GOMODCACHE=${GOPATH}/gomod
export PATH=$HOME/.cargo/bin:$HOME/.autojump/bin:$HOME/.fzf/bin:$HOME/.local/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$GOBIN
export LD_LIBRARY_PATH=${APP_PATH}/ImageMagick/lib:/usr/local/lib:${APP_PATH}/ffmpeg/lib
#export C_INCLUDE_PATH=
export CPLUS_INCLUDE_PATH=${APP_PATH}/ImageMagick/include/ImageMagick-7:${APP_PATH}/ffmpeg/include
export MCFLY_KEY_SCHEME=vim
export MCFLY_FUZZY=true
export MCFLY_RESULTS=50
export BAT_THEME="Coldark-Dark"
export TERM=xterm-256color
export GIT_TERMINAL_PROMPT=1

## PS1
COLOR_RED='\[\033[1;31m\]'
COLOR_GREEN='\[\033[1;32m\]'
COLOR_YELLOW='\[\033[1;33m\]'
COLOR_MAGENTA='\[\033[1;35m\]'
COLOR_CYAN='\[\033[1;36m\]'
COLOR_WHITE='\[\033[1;37m\]'
COLOR_NONE='\[\033[m\]'

#PS1_USER="${CONTROL_CODE_PREFIX}${CONTROL_CODE_HIGHLIGHT}${CONTROL_CODE_SPERATOR}${TEXT_COLOR_PINK}${CONTROL_CODE_SUFFIX}\u${CONTROL_CODE_PREFIX}${CONTROL_CODE_CLOSE}${CONTROL_CODE_SUFFIX}"
#PS1_HOST="${CONTROL_CODE_PREFIX}${CONTROL_CODE_HIGHLIGHT}${CONTROL_CODE_SPERATOR}${TEXT_COLOR_DEEP_BLUE}${CONTROL_CODE_SUFFIX}\h${CONTROL_CODE_PREFIX}${CONTROL_CODE_CLOSE}${CONTROL_CODE_SUFFIX}"
#PS1_PWD="${CONTROL_CODE_PREFIX}${CONTROL_CODE_HIGHLIGHT}${CONTROL_CODE_SPERATOR}${TEXT_COLOR_YELLOW}${CONTROL_CODE_SUFFIX}\W${CONTROL_CODE_PREFIX}${CONTROL_CODE_CLOSE}${CONTROL_CODE_SUFFIX}"
PS1_SENTENCE="${CONTROL_CODE_PREFIX}${CONTROL_CODE_HIGHLIGHT}${CONTROL_CODE_SPERATOR}${TEXT_COLOR_RED}${CONTROL_CODE_SUFFIX}[\$(echo_sentence)]${CONTROL_CODE_PREFIX}${CONTROL_CODE_CLOSE}${CONTROL_CODE_SUFFIX}"
PS1_DATE="${CONTROL_CODE_PREFIX}${CONTROL_CODE_HIGHLIGHT}${CONTROL_CODE_SPERATOR}${TEXT_COLOR_YELLOW}${CONTROL_CODE_SUFFIX}[\$(echo_date)]${CONTROL_CODE_PREFIX}${CONTROL_CODE_CLOSE}${CONTROL_CODE_SUFFIX}"
PS1_GIT="${CONTROL_CODE_PREFIX}${CONTROL_CODE_HIGHLIGHT}${CONTROL_CODE_SPERATOR}${TEXT_COLOR_GREEN}${CONTROL_CODE_SUFFIX}\$(parse_git_branch)${CONTROL_CODE_PREFIX}${CONTROL_CODE_CLOSE}${CONTROL_CODE_SUFFIX}"
PS1_STATUS="${CONTROL_CODE_PREFIX}${CONTROL_CODE_HIGHLIGHT}${CONTROL_CODE_SPERATOR}${TEXT_COLOR_DEEP_BLUE}${CONTROL_CODE_SUFFIX}[\$(echo_last_status \$?)]${CONTROL_CODE_PREFIX}${CONTROL_CODE_CLOSE}${CONTROL_CODE_SUFFIX}"

#export PS1="${PS1_STATUS}\u@\h \W ${PS1_SENTENCE} ${PS1_DATE}${PS1_GIT} \$"
export PS1="${PS1_STATUS}\u@\h \W ${PS1_DATE}${PS1_GIT} \$"
